### ISSUE TITLE
[kinetic] support behavior_tree_visualizer on kinetic

### ISSUE THREAD

**Issue by ompugao** [SSL-Roots/CON-SAI#15]
xdotがqt4にばっちり食いこんでいて、monkey patchがしんどい
~~まだ作業中です~~
終わりました

https://github.com/ompugao/CON-SAI/tree/fix_btv_error
https://github.com/ompugao/xdot/tree/kinetic-devel

**Comment by ompugao** [comment]
ref https://github.com/7oei/robocup-ssl/issues/1

**Comment by ompugao** [comment]
上記repositoryの変更でindigo/kinetic両方で動くと思います（indigo未確認)
jbohren/xdotの開発はstopしてしまっているので、おそらくそちらにはmergeしてもらえないです
よって、Rootsさんの方でforkしてそちらをCON-SAIのsubmoduleに加えてもらうことは可能でしょうか

**Comment by ShotaAk** [comment]
修正ありがとうございます！！！
こちらで対応するまでにちょっと時間をください…

**Comment by ShotaAk** [comment]
behavior_visualizerはひとまず作成中止します。。。（いろいろやってもらってありがとうございます）

代わりのvisualizerを作成予定です。

ここはcloseします。
