### ISSUE TITLE
[kinetic] Y-axis movement of the robot4 is strange at Tutorial

### ISSUE THREAD

**Issue by AtsukiKawahara** [SSL-Roots/CON-SAI#16]
Kineticで[チュートリアル](https://github.com/SSL-Roots/CON-SAI/blob/master/Tutorial.md)通りに進めた所
「Referee BoxでStop Game -> Kick Off 」のタイミングでRobot4のy軸指令値 /robot_4/cmd_vel があやしく、味方のRobot1とぶつかる現象が発生
※indigoでは正しく動作中

テスト動画
・kinetic
https://drive.google.com/file/d/0B5oEuTcLOvlDaTZSSlU5cTA5dGM/view?usp=sharing
・indogo
https://drive.google.com/file/d/0B5oEuTcLOvlDYTlfakpySm9yUkk/view?usp=sharing

まとめ
・Robot3は正しく動作している
・Robot4のトピック/robot_4/avoid_pointが常に0付近でしか出力されていない

作業中です

**Comment by AtsukiKawahara** [comment]
この/robot_4/cmd_vel を作っているtrapezoidal_control_node の関係付近が怪しいと思われる。

受け取ってるトピック（subscrib）
/move_base_simple/goal
/move_base_simple/target_velocity
/odom
/ai_status
/existing_enemies_id
/existing_friends_id
/ball_observer/estimation

計算した後に出力してるトピック （pub）
/cmd_vel
/avoid_point

コードの途中にて、
output.y = avoidPos.imag();
を
output.y = avoidPos.imag()-0.1;
に変更したところ，Robot4，それから3,5が常時手前側に移動することは確認しました

**Comment by AtsukiKawahara** [comment]
解決しました．

CON-SAI/trapezoidal_control/src/transformation.h

内の

Tool::normalize()

ですがreturnがないため，おそらくgccのver違いによって出てくる値が変わっていました．
``transformation.h
namespace Tool{
    inline double normalize(double angle){
        while(angle > M_PI){
            angle -= 2.0*M_PI;
        }
        while(angle < -M_PI){
            angle += 2.0*M_PI;
        }
        return angle;
    }
``
とする事でKineticでも正しく動きました．

IndigoとKinetic共通になると思うのでmasterから修正お願いできますでしょうか？

**Comment by ShotaAk** [comment]
ありがとうございます！修正します！
