### ISSUE TITLE
ネットワークインタフェースが複数あるとき、通信できない場合がある。

### ISSUE THREAD

**Issue by ShotaAk** [SSL-Roots/CON-SAI#8]
[grsim_wrapperのmulticast](https://github.com/SSL-Roots/CON-SAI/blob/master/grsim_wrapper/scripts/multicast.py)と、[ssl_refboxのmulticast](https://github.com/SSL-Roots/CON-SAI/blob/master/ssl_refbox_wrapper/src/multicast.py)
は、ネットワークインタフェース(eth0, wlan0, etc...)を意識せず、アドレスとポートだけを設定すればマルチキャスト受信できるように書かれている。

しかし、有線LANポートが複数あると、eth0とeth1が共存してしまい、eth1がvisionサーバと繋がると通信ができない。

インタフェースをrosparamで設定できるようにすれば問題は低減できるが、ラップトップ等で有線/無線を頻繁に切り替えて使用する場合に手間がかかる。

解決方法は下の通り
* 現状を変えずコメント or Readmeに注意を書く
* インタフェースをrosparamで設定できるようにする
* もっとスマートな実装を検討する。　<- いまここ

**Comment by ompugao** [comment]
（もし設定されていたら）$ROS_IPに合致するインターフェイスをつかうのはいかがですか

**Comment by ShotaAk** [comment]
@ompugao  ありがとうございます！
ROS_IPを使う方向で実装中です。
